version: "3.7"

services:
  mariadb:
    container_name: mariadb_insta
    image: mariadb/server
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "hyecheon"
      MARIADB_ROOT_HOST: '%'
      MARIADB_USER: "insta"
      MARIADB_PASSWORD: "insta"
      MARIADB_DATABASE: "insta"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_insta
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka_insta
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./data/kafka/docker.sock:/var/run/docker.sock
