###
POST http://localhost:8080/api/v1/subscribes/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbnR0ZTMiLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjQwMDYxOTE3LCJ1c2VySWQiOjN9.JLqOfghzvVgBtsu5Eyurp6pp3s82WBc4tXOVI-8XKa4

###
DELETE http://localhost:8080/api/v1/subscribe/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbnR0ZSIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE2MzkxNDgxNjQsInVzZXJJZCI6MX0.TOugfqZT2c0vGnUv6sS8mb4HsQkF95CFHvNcaiszo74

###
GET http://localhost:8080/api/v1/subscribes/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbnR0ZTIiLCJyb2xlIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjM5NDczNTMxLCJ1c2VySWQiOjJ9.bXXD7Zl445DceSa_l5AHycWU0ElWBpdbCWJ4a0oKd5s